
// Create admin 
function createAdminAccount() {
    let accounts = localStorage.getItem("accounts");
    if (!accounts) {
        accounts = [];
        accounts.push({
            fullname: "Huỳnh Tấn Dương",
            phone: "0123456789",
            password: "123456789",
            address: '',
            email: '',
            status: 1,
            join: new Date(),
            cart: [],
            userType: 1
        })
        localStorage.setItem('accounts', JSON.stringify(accounts));
    }
}
function createProducts() {
    let products = localStorage.getItem("products");
    if (!products) {
        products = [];
        products.push({
            masp: 1, 
            tensp: "Manchester United Kit", 
            description:"Áo đấu sân nhà của đội Manchester United",
            size:"S",
            price: 100000,
            stock:32,
            team:"MU",
            national:'',
            image_url: "../img/mu1.png", 
            status:true,
        },
        {
            masp: 2, 
            tensp: "Manchester City Kit", 
            description:"Áo đấu sân nhà của đội Manchester City",
            size:"S",
            price: 100000,
            stock:32,
            team:"MC",
            national:'',
            image_url: "../img/mc1.png", 
            status:true,
        },
        {
            masp: 3, 
            tensp: "Barcelona Kit", 
            description:"Áo đấu sân nhà của đội Barcelona",
            size:"S",
            price: 100000,
            stock:32,
            team:"BC",
            national:'',
            image_url: "../img/bar1.png", 
            status:true,
        },
        {
            masp: 4, 
            tensp: "Real Marid", 
            description:"Áo đấu sân nhà của đội Real Marid",
            size:"S",
            price: 100000,
            stock:32,
            team:"RM",
            national:'',
            image_url: "../img/real1.png", 
            status:true,
        },
        {
            masp: 5, 
            tensp: "Al-Nassr Kit", 
            description:"Áo đấu sân nhà của đội Al-Nassr",
            size:"S",
            price: 100000,
            stock:32,
            team:"AN",
            national:'',
            image_url: "../img/al1.png", 
            status:true,
        },
        {
            masp: 6, 
            tensp: "Manchester United Kit", 
            description:"Áo đấu sân khách của đội Manchester United",
            size:"S",
            price: 100000,
            stock:32,
            team:"MU",
            national:'',
            image_url: "../img/mu2.png", 
            status:true,
        },
        {
            masp: 7, 
            tensp: "Manchester City Kit", 
            description:"Áo đấu sân khách của đội Manchester City",
            size:"S",
            price: 100000,
            stock:32,
            team:"MC",
            national:'',
            image_url: "../img/mc2.png", 
            status:true,
        },
        {
            masp: 8, 
            tensp: "Real Marid Kit", 
            description:"Áo đấu sân khách của đội Real Marid",
            size:"S",
            price: 100000,
            stock:32,
            team:"RM",
            national:'',
            image_url: "../img/real2.png", 
            status:true,
        },
        {
            masp: 9, 
            tensp: "Barcelona Kit", 
            description:"Áo đấu sân khách của đội Barcelona",
            size:"S",
            price: 100000,
            stock:32,
            team:"BC",
            national:'',
            image_url: "../img/bar2.png", 
            status:true,
        },
        {
            masp: 10, 
            tensp: "Al-Nassr Kit", 
            description:"Áo đấu sân khách của đội Al-Nassr",
            size:"S",
            price: 100000,
            stock:32,
            team:"AN",
            national:'',
            image_url: "../img/al2.png", 
            status:true,
        },
        {
            masp: 11, 
            tensp: "Việt Nam", 
            description:"Áo đấu đội tuyển quốc gia Việt Nam",
            size:"S",
            price: 100000,
            stock:32,
            team:"VN",
            national:'',
            image_url: "../img/vn.png", 
            status:true,
        },
        {
            masp: 12, 
            tensp: "Anh", 
            description:"Áo đấu đội bóng quốc gia Tam sư",
            size:"S",
            price: 100000,
            stock:32,
            team:"EN",
            national:'',
            image_url: "../img/eng.png", 
            status:true,
        },
        {
            masp: 13, 
            tensp: "Pháp", 
            description:"Áo đấu đội bóng Gà trống Gaulois",
            size:"S",
            price: 100000,
            stock:32,
            team:"PR",
            national:'',
            image_url: "../img/phap.png", 
            status:true,
        },
        {
            masp: 14, 
            tensp: "Argentina", 
            description:"Áo đấu của nhà vô địch WorldCup 2022",
            size:"S",
            price: 100000,
            stock:32,
            team:"AG",
            national:'',
            image_url: "../img/arg.png", 
            status:true,
        },
        {
            masp: 15, 
            tensp: "Bồ Đào Nha", 
            description:"Áo đấu của đội bóng Selecao châu Âu",
            size:"S",
            price: 100000,
            stock:32,
            team:"PO",
            national:'',
            image_url: "../img/por.png", 
            status:true,
        },
    )
        localStorage.setItem('products', JSON.stringify(products));
    }
}

window.onload = createProducts();
window.onload = createAdminAccount();